# -*- coding: utf-8 -*-
"""Lab_4_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Te_huNcOezctgISFazzBVL6rZhZAbSWG

b)
"""

import warnings
from transformers import pipeline

# Приглушуємо попередження для чистоти виводу
warnings.filterwarnings("ignore")

def demo_zero_shot_classification():
    print("--- 1. Zero-Shot Classification (Класифікація без навчання) ---")

    # Використовуємо потужну мультимовну модель mDeBERTa, яка чудово розуміє українську
    # Model: MoritzLaurer/mDeBERTa-v3-base-mnli-xnli
    classifier = pipeline(
        "zero-shot-classification",
        model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli"
    )

    sequence = "Інтерфейс цієї програми дуже зручний, але ціна зависока для звичайного користувача."
    candidate_labels = ["технології", "політика", "фінанси", "відгук про продукт"]

    print(f"Текст: {sequence}")
    print(f"Категорії: {candidate_labels}")

    result = classifier(sequence, candidate_labels, multi_label=False)

    print("\nРезультат:")
    for label, score in zip(result['labels'], result['scores']):
        print(f"- {label}: {score:.4f}")
    print("\n")


def demo_summarization():
    print("--- 2. Summarization (Сумаризація тексту) ---")

    # Використовуємо mT5, яка була донавчена на наборі даних XLSum (включає українську BBC)
    # Model: csebuetnlp/mT5_multilingual_XLSum
    summarizer = pipeline(
        "summarization",
        model="csebuetnlp/mT5_multilingual_XLSum",
        tokenizer="csebuetnlp/mT5_multilingual_XLSum"
    )

    # Довгий текст про Київську Русь
    article_text = """
    Київська Русь — середньовічна монархічна держава у Східній Європі зі столицею в Києві.
    Вона виникла в IX столітті в результаті об'єднання східнослов'янських племен під владою династії Рюриковичів.
    У часи свого розквіту за правління Володимира Великого та Ярослава Мудрого держава простягалася від Чорного моря
    на півдні до Білого моря на півночі, і від Карпат на заході до Волги на сході.
    Прийняття християнства у 988 році стало ключовим моментом, що ввів Русь у коло європейських цивілізацій,
    сприяючи розвитку культури, писемності та архітектури. Проте, через феодальну роздробленість та монгольську навалу
    в XIII столітті, держава занепала.
    """

    print("Оригінальний текст (уривок):")
    print(article_text.strip()[:150] + "...")

    # Генеруємо короткий підсумок
    summary = summarizer(article_text, max_length=60, min_length=10, do_sample=False)

    print("\nРезультат (Сумаризація):")
    print(summary[0]['summary_text'])
    print("\n")


def demo_translation():
    print("--- 3. Translation (Переклад) ---")

    # Використовуємо спеціалізовану модель від Helsinki-NLP для перекладу з української на англійську
    # Model: Helsinki-NLP/opus-mt-uk-en
    translator = pipeline(
        "translation_uk_to_en",
        model="Helsinki-NLP/opus-mt-uk-en"
    )

    uk_text = "Штучний інтелект стрімко розвивається і змінює світ навколо нас."

    print(f"Оригінал: {uk_text}")

    translation = translator(uk_text)

    print(f"Переклад (EN): {translation[0]['translation_text']}")
    print("\n")

if __name__ == "__main__":
    print("Завантаження моделей та запуск демо...\n")

    # Запуск по черзі
    demo_zero_shot_classification()
    demo_summarization()
    demo_translation()

    print("Демонстрацію завершено.")

"""c)"""

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image


def generate_image_text_to_image():
    """
    Демонстрація базової задачі Text-to-Image (Текст -> Зображення).
    Використовується модель Stable Diffusion v1.5.
    """

    print("--- Початок ініціалізації Text-to-Image Pipeline ---")

    # 1. Вибір пристрою (CUDA для NVIDIA GPU, MPS для Mac M1/M2, або CPU)
    device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
    print(f"Використовується пристрій: {device}")

    # 2. Завантаження моделі
    # Ми використовуємо популярну версію Stable Diffusion 1.5
    model_id = "runwayml/stable-diffusion-v1-5"

    # Якщо є GPU, використовуємо float16 для економії пам'яті та швидкості
    if device == "cuda":
        pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
    else:
        pipe = StableDiffusionPipeline.from_pretrained(model_id)

    # Переміщення пайплайну на вибраний пристрій
    pipe = pipe.to(device)

    # pipe.enable_attention_slicing()

    # 3. Налаштування параметрів генерації
    # Промпт (опис зображення) англійською мовою працює найкраще
    prompt = "A futuristic cyberpunk city specifically in Kyiv, neon lights, flying cars, highly detailed, 8k resolution, cinematic lighting"
    negative_prompt = "blurry, bad quality, distorted, ugly, low resolution"

    print(f"Генеруємо зображення за запитом: '{prompt}'...")

    # 4. Генерація
    # num_inference_steps - кількість кроків "шуму"
    # guidance_scale - наскільки суворо слідувати тексту
    image = pipe(
        prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5
    ).images[0]

    # 5. Виведення результату
    # Зберігаємо файл (про всяк випадок) та відкриваємо його у звичайному переглядачі
    output_filename = "generated_kyiv_cyberpunk.png"
    image.save(output_filename)
    print(f"Зображення збережено як: {output_filename}")

    print("Відкриваємо зображення...")
    image.show()