# -*- coding: utf-8 -*-
"""Lab_4_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Te_huNcOezctgISFazzBVL6rZhZAbSWG

b)
"""

import warnings
from transformers import pipeline

# Приглушуємо попередження для чистоти виводу
warnings.filterwarnings("ignore")

def demo_zero_shot_classification():
    print("--- 1. Zero-Shot Classification (Класифікація без навчання) ---")

    # Використовуємо потужну мультимовну модель mDeBERTa, яка чудово розуміє українську
    # Model: MoritzLaurer/mDeBERTa-v3-base-mnli-xnli
    classifier = pipeline(
        "zero-shot-classification",
        model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli"
    )

    sequence = "Інтерфейс цієї програми дуже зручний, але ціна зависока для звичайного користувача."
    candidate_labels = ["технології", "політика", "фінанси", "відгук про продукт"]

    print(f"Текст: {sequence}")
    print(f"Категорії: {candidate_labels}")

    result = classifier(sequence, candidate_labels, multi_label=False)

    print("\nРезультат:")
    for label, score in zip(result['labels'], result['scores']):
        print(f"- {label}: {score:.4f}")
    print("\n")


def demo_summarization():
    print("--- 2. Summarization (Сумаризація тексту) ---")

    # Використовуємо mT5, яка була донавчена на наборі даних XLSum (включає українську BBC)
    # Model: csebuetnlp/mT5_multilingual_XLSum
    summarizer = pipeline(
        "summarization",
        model="csebuetnlp/mT5_multilingual_XLSum",
        tokenizer="csebuetnlp/mT5_multilingual_XLSum"
    )

    # Довгий текст про Київську Русь
    article_text = """
    Київська Русь — середньовічна монархічна держава у Східній Європі зі столицею в Києві.
    Вона виникла в IX столітті в результаті об'єднання східнослов'янських племен під владою династії Рюриковичів.
    У часи свого розквіту за правління Володимира Великого та Ярослава Мудрого держава простягалася від Чорного моря
    на півдні до Білого моря на півночі, і від Карпат на заході до Волги на сході.
    Прийняття християнства у 988 році стало ключовим моментом, що ввів Русь у коло європейських цивілізацій,
    сприяючи розвитку культури, писемності та архітектури. Проте, через феодальну роздробленість та монгольську навалу
    в XIII столітті, держава занепала.
    """

    print("Оригінальний текст (уривок):")
    print(article_text.strip()[:150] + "...")

    # Генеруємо короткий підсумок
    summary = summarizer(article_text, max_length=60, min_length=10, do_sample=False)

    print("\nРезультат (Сумаризація):")
    print(summary[0]['summary_text'])
    print("\n")


def demo_translation():
    print("--- 3. Translation (Переклад) ---")

    # Використовуємо спеціалізовану модель від Helsinki-NLP для перекладу з української на англійську
    # Model: Helsinki-NLP/opus-mt-uk-en
    translator = pipeline(
        "translation_uk_to_en",
        model="Helsinki-NLP/opus-mt-uk-en"
    )

    uk_text = "Штучний інтелект стрімко розвивається і змінює світ навколо нас."

    print(f"Оригінал: {uk_text}")

    translation = translator(uk_text)

    print(f"Переклад (EN): {translation[0]['translation_text']}")
    print("\n")

if __name__ == "__main__":
    print("Завантаження моделей та запуск демо...\n")

    # Запуск по черзі
    demo_zero_shot_classification()
    demo_summarization()
    demo_translation()

    print("Демонстрацію завершено.")

""" Завантаження моделей та запуск демо...

--- 1. Zero-Shot Classification (Класифікація без навчання) ---
config.json:  1.07k/? [00:00<00:00, 84.5kB/s]model.safetensors: 100% 558M/558M [00:07<00:00, 140MB/s]tokenizer_config.json:  1.26k/? [00:00<00:00, 126kB/s]spm.model: 100% 4.31M/4.31M [00:02<00:00, 1.46MB/s]tokenizer.json: 100% 16.3M/16.3M [00:02<00:00, 6.79MB/s]added_tokens.json: 100% 23.0/23.0 [00:00<00:00, 2.57kB/s]special_tokens_map.json: 100% 286/286 [00:00<00:00, 35.0kB/s]Device set to use cuda:0
Текст: Інтерфейс цієї програми дуже зручний, але ціна зависока для звичайного користувача.
Категорії: ['технології', 'політика', 'фінанси', 'відгук про продукт']

Результат:
- фінанси: 0.6149
- технології: 0.3311
- відгук про продукт: 0.0492
- політика: 0.0048


--- 2. Summarization (Сумаризація тексту) ---
config.json: 100% 730/730 [00:00<00:00, 47.4kB/s]pytorch_model.bin: 100% 2.33G/2.33G [00:27<00:00, 44.4MB/s]model.safetensors: 100% 2.33G/2.33G [00:51<00:00, 59.5MB/s]tokenizer_config.json: 100% 375/375 [00:00<00:00, 42.9kB/s]spiece.model: 100% 4.31M/4.31M [00:04<00:00, 1.23MB/s]special_tokens_map.json: 100% 65.0/65.0 [00:00<00:00, 2.14kB/s]You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Device set to use cuda:0
Оригінальний текст (уривок):
Київська Русь — середньовічна монархічна держава у Східній Європі зі столицею в Києві. 
    Вона виникла в IX столітті в результаті об'єднання східнос...

Результат (Сумаризація):
Київська Русь - одна з найбільших монархічних держав у Східній Європі.


--- 3. Translation (Переклад) ---
config.json:  1.38k/? [00:00<00:00, 60.7kB/s]pytorch_model.bin: 100% 305M/305M [00:06<00:00, 62.7MB/s]generation_config.json: 100% 293/293 [00:00<00:00, 21.2kB/s]tokenizer_config.json: 100% 42.0/42.0 [00:00<00:00, 4.90kB/s]model.safetensors: 100% 305M/305M [00:40<00:00, 5.44MB/s]source.spm: 100% 1.01M/1.01M [00:00<00:00, 21.8MB/s]target.spm: 100% 809k/809k [00:00<00:00, 45.6MB/s]vocab.json:  2.37M/? [00:00<00:00, 72.1MB/s]Device set to use cuda:0
Оригінал: Штучний інтелект стрімко розвивається і змінює світ навколо нас.
Переклад (EN): The artificial intelligence is rapidly developing and is changing the world around us.


Демонстрацію завершено.
"""

"""c)"""

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image


def generate_image_text_to_image():
    """
    Демонстрація базової задачі Text-to-Image (Текст -> Зображення).
    Використовується модель Stable Diffusion v1.5.
    """

    print("--- Початок ініціалізації Text-to-Image Pipeline ---")

    # 1. Вибір пристрою (CUDA для NVIDIA GPU, MPS для Mac M1/M2, або CPU)
    device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
    print(f"Використовується пристрій: {device}")

    # 2. Завантаження моделі
    # Ми використовуємо популярну версію Stable Diffusion 1.5
    model_id = "runwayml/stable-diffusion-v1-5"

    # Якщо є GPU, використовуємо float16 для економії пам'яті та швидкості
    if device == "cuda":
        pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
    else:
        pipe = StableDiffusionPipeline.from_pretrained(model_id)

    # Переміщення пайплайну на вибраний пристрій
    pipe = pipe.to(device)

    # pipe.enable_attention_slicing()

    # 3. Налаштування параметрів генерації
    # Промпт (опис зображення) англійською мовою працює найкраще
    prompt = "A futuristic cyberpunk city specifically in Kyiv, neon lights, flying cars, highly detailed, 8k resolution, cinematic lighting"
    negative_prompt = "blurry, bad quality, distorted, ugly, low resolution"

    print(f"Генеруємо зображення за запитом: '{prompt}'...")

    # 4. Генерація
    # num_inference_steps - кількість кроків "шуму"
    # guidance_scale - наскільки суворо слідувати тексту
    image = pipe(
        prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=30,
        guidance_scale=7.5
    ).images[0]

    # 5. Виведення результату
    # Зберігаємо файл (про всяк випадок) та відкриваємо його у звичайному переглядачі
    output_filename = "generated_kyiv_cyberpunk.png"
    image.save(output_filename)
    print(f"Зображення збережено як: {output_filename}")

    print("Відкриваємо зображення...")
    image.show()

